### ISSUE TITLE
在springboot-druid中貌似沒有使用到读写分离

### ISSUE THREAD

**Issue by guodidi** [Lengchuan/SpringBoot-Study#1]
阅读完程序之后，应该是没有使用到读写分离，因为你的mapper包下根本就没有wrire，read1，read2包名，因此可以确定的是，没有使用到读写分离。请确认我所描述的情况，谢谢

**Comment by Lengchuan** [comment]
@guodidi 
我这里为了省事，都是使用master来作为write、read1、read2的数据源，所以在mapper文件下没有相对应的包，至于读写分离，我是为了说明要怎么在结合springboot-druid在软件层面配置，读写分离还需要主从的配置，但这个不是我们讨论的主题了，我这里这是用多个库来模拟这么一种情况，非常感谢所提的问题，我之后会补充说明一下，谢谢！
